# Rasoi Radar — developer task runner.
# Usage: `make <target>`. Run `make help` for the list.

.DEFAULT_GOAL := help
.PHONY: help install dev dev-web dev-api test test-web test-api lint typecheck migrate migration seed

API_DIR := apps/api
PY := $(API_DIR)/.venv/bin/python
PIP := $(API_DIR)/.venv/bin/pip

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

install: ## Install web (pnpm) and api (venv) dependencies
	pnpm install
	python3 -m venv $(API_DIR)/.venv
	$(PIP) install --upgrade pip
	$(PIP) install -e "$(API_DIR)[dev]"

dev: ## Run web (:3000) and api (:8000) together
	@echo "Starting web on :3000 and api on :8000 ..."
	@$(MAKE) -j2 dev-web dev-api

dev-web: ## Run the Next.js dev server on :3000
	pnpm --filter @rasoi/web dev

dev-api: ## Run the FastAPI dev server on :8000
	cd $(API_DIR) && .venv/bin/uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

test: test-api test-web ## Run all tests

test-web: ## Run vitest
	pnpm --filter @rasoi/web test

test-api: ## Run pytest
	cd $(API_DIR) && .venv/bin/pytest

lint: ## Lint web (eslint) and api (ruff)
	pnpm --filter @rasoi/web lint
	cd $(API_DIR) && .venv/bin/ruff check .

typecheck: ## Typecheck web (tsc) and api (mypy)
	pnpm -r typecheck
	cd $(API_DIR) && .venv/bin/mypy app

migrate: ## Apply DB migrations to head
	cd $(API_DIR) && .venv/bin/alembic upgrade head

migration: ## Create a new autogenerated migration: make migration m="message"
	cd $(API_DIR) && .venv/bin/alembic revision --autogenerate -m "$(m)"

seed: ## Seed the database (idempotent)
	cd $(API_DIR) && .venv/bin/python -m scripts.seed
